name: Build and Push Containers to AWS ECR

on:
  workflow_run:
    workflow: ["Run Tests"]
    types:
      - completed



jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URI }}

      - name: Build Docker image
        run: docker build -t ci-cd-app .
        
      - name: Tag image for ECR
        run: docker tag ci-cd-app:latest ${{ secrets.ECR_REPO_URI }}:latest

      - name: Push image to ECR
        run: docker push ${{ secrets.ECR_REPO_URI }}:latest